### ISSUE TITLE
(ADD_SITE): Decentrealized Web Hosting 

### ISSUE THREAD

**Issue by imabutahersiddik** [dalisoft/awesome-hosting#15]
## Type

- [x] Free Hosting
- [x] PHP
- [x] MySQL
- [x] Postgress Sql
- [x] FTP
- [x] Cpanel 
- [x] Free Subdomain 
- [ ] VPS
- [x] Static hosting

## Description

Decentrealized Web hosting offer 5GB free hosting with unlimited bandwidth. 

## Link

https://www.decentrealizedweb.xyz/free-hosting

**Comment by dalisoft** [comment]
@imabutahersiddik Thank you for offering but we can't add PHP only hosting and this site SSL even not trusted so sorry

**Comment by imabutahersiddik** [comment]
Please try now, ssl has been fixed: https://decentrealizedweb.xyz/free-hosting
