### ISSUE TITLE
[WRONG INFO]: Deta is unlimited

### ISSUE THREAD

**Issue by abdelhai** [dalisoft/awesome-hosting#3]
## Reason

- [x] Wrong information
- [ ] Typo error
- [ ] License violation

## Type

- [ ] Node.js Hosting
- [ ] VPS
- [ ] Static hosting

## Description

Hi, CEO of Deta here, thanks for including us! Deta gives you unlimited Micros (apps), databases and cloud drives. Deta also recently removed the limits and the paid tier and so became %100 free for everyone.

## Link

https://www.deta.sh/pricing

**Comment by dalisoft** [comment]
Hey there @abdelhai 
I'm happy to see you here
Thank you for best service.

Soon i'll change information

**Comment by dalisoft** [comment]
@abdelhai It's correct now?

**Comment by abdelhai** [comment]
Yes, thank you for the quick edit 😊🙏
@dalisoft

**Comment by dalisoft** [comment]
@abdelhai Thank you for great service
