### ISSUE TITLE
AWS is not free

### ISSUE THREAD

**Issue by 89z** [dalisoft/awesome-hosting#6]
AWS does have a free trial, but after a year its paid

https://github.com/dalisoft/awesome-hosting#web-services-platform

**Comment by dalisoft** [comment]
@89z Thank you for checking the correct information. Is #7 fix solved the wrong information? Thank you again

**Comment by 89z** [comment]
Yes, I think that is more accurate. Thank you!

**Comment by dalisoft** [comment]
Thank you. You welcome and happy to see your new issues related to information or pull requests if you want. Have a great day
